name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-emacs-org-notes:
    runs-on: ubuntu-latest
    container: alpine:3.13.4
    steps:
      - uses: actions/checkout@v2
      - name: Install emacs
        run: apk --update add emacs        
      - name: Render notes into html
        run: emacs go.org --batch -Q --load minimal-setup-to-export-org-to-html.el -f org-html-export-to-html --kill; mkdir output; mv go.html output/
      - name: Install git
        run: apk add git
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updating How-Do-I.html"
      - name: push code to master
        run: git push origin HEAD:master
