name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-emacs-org-notes:
    runs-on: ubuntu-latest
    container: alpine:3.13.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create/update text file
        run: echo "var=x" > test.txt
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "commit message"
          git push
